<a href="https://colab.research.google.com/github/koushik7095/python_lab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
6(a)Find the position of missing values in numpy array
import numpy as np
array=np.array([1,2,np.missing,4,np.missing,6])
mising_position=np.where(np.ismissing())

In [ ]:
#create a numpy array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
(a)#1-D Array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
(b)#create a boolean array
import numpy as np
arr=np.array([1,0,1,0,0,1,0])
print(f'Original Array:{arr}')
bool_arr=np.array(arr,dtype='bool')
print(f'boolean array:{bool_arr}')

Original Array:[1 0 1 0 0 1 0]
boolean array:[ True False  True False False  True False]


In [ ]:
(c)#extract items that satisfy a given condition from 1-D array
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[arr%2==1])

[1 3 5 7 9]


In [ ]:
(d)#replace items that satisfy a condition with another value in numpy array
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
(e)#replace items that satisfy a condition without affecting the original array
import numpy as np
arr1 = np.array([30,23,67,12,8,9,4])
arr1[arr1 > 30] = 100
print(arr1)

[ 30  23 100  12   8   9   4]


In [ ]:
(f)#reshape an array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
(g)#extract all numbers between a given range from a numpy array
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[np.where((a >= 5) & (a <= 10))])

[ 6  9 10]


In [ ]:
3(a)#stack two arrays vertically
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_array = np.vstack((arr1, arr2))
print(stacked_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
(b)#stack two arrays horizontally
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_array = np.hstack((arr1, arr2))
print(stacked_array)

[1 2 3 4 5 6]


In [ ]:
(c)#get the common items between two python numpy arrays
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 5, 6, 7, 8])
common_items = np.intersect1d(arr1, arr2)
print(common_items)

[3 5]


In [ ]:
#remove from one array those items that exist in another
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 5, 6, 7, 8])
arr1 = arr1[~np.isin(arr1, arr2)]
print(arr1)

[1 2 4]


In [ ]:
#Get the position where elements of two arrays match
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 5, 6, 7, 8])
common_items = np.intersect1d(arr1, arr2)
print(f"common items: {common_items}")
positions = np.where(arr1==arr2)
print(positions)

common items: [1 5]
(array([0]),)


In [ ]:
(a)#convert an array of arrays in to a flat1d array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [ ]:
(b)#swap two columns in a 2d numpy array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[:, [1, 2]] = arr[:, [2, 1]]
print(arr)

[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [ ]:
(a)#compute the mean,median, standard deviation of a numpy array
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [ ]:
(b)#find the percentile scores of a numpy array
import numpy as np
data=np.array([1,2,3,4,5,6,7,8,9,10])
percentiles = np.percentile(data, [25,50,75])
print("25th percentile:", percentiles[0])
print("50th percentile (median):", percentiles[1])
print("75th percentile:", percentiles[2])

25th percentile: 3.25
50th percentile (median): 5.5
75th percentile: 7.75


In [ ]:
(c)#compute the euclidean distance between two arrays
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
distance=np.linalg.norm(arr1-arr2)
print(f"Euclidean Distance:{distance}")

Euclidean Distance:5.196152422706632


In [ ]:
#find the correlation between two columns of a numpy array
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10])
y=np.array([7,6,5,4,5,6,7,8,9,10])
a=np.corrcoef(x,y)
print(a)

[[1.         0.70927291]
 [0.70927291 1.        ]]


In [ ]:
#probabilistic sampling in numpy
import numpy as np
data = ['apple', 'banana', 'orange', 'grape']
probabilities = [0.3, 0.2, 0.4, 0.1]
samples = np.random.choice(data, size=5, replace=True, p=probabilities)
print(samples)

['apple' 'apple' 'orange' 'apple' 'apple']


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
window_size=3
moving_average=np.convolve(arr,np.ones(window_size)/window_size,'valid')
print(moving_average)

[2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#6(a)Find the position of missing values in numpy array
import numpy as np
array = np.array([1, 2, np.nan, 4, np.nan, 6])
missing_positions = np.where(np.isnan(array))
print(missing_positions)

(array([2, 4]),)


In [ ]:
#(b)Drop rows that contain a missing value from a numpy array
import numpy as np
example_array=np.array([[1,2,3],
                       [4,np.nan,6],
                       [7,8,9]])
rows_without_missing=np.all(np.isfinite(example_array), axis=1)
filtered_array=example_array[rows_without_missing]
print(filtered_array)

[[1. 2. 3.]
 [7. 8. 9.]]


In [ ]:
#(c)replace all missing values with 0 in a numpy array
import numpy as np
example_array=np.array([1,2,np.nan,4,5,np.nan])
example_array[np.isnan(example_array)]=0
print(example_array)

[1. 2. 0. 4. 5. 0.]


In [ ]:
#(d)Drop all missing values from a numpy array
import numpy as np
example_array=np.array([1,2,np.nan,4,5,np.nan])
filtered_array=example_array[~np.isnan(example_array)]
print(filtered_array)

[1. 2. 4. 5.]


In [ ]:
#7(a)normalize an array so that values range exactly between 0 and 1
import numpy as np
def normalize_array(arr):
  min_val=np.min(arr)
  max_val=np.max(arr)
  normalized_arr=(arr-min_val)/(max_val-min_val)
  return normalized_arr
example_array=np.array([1,2,3,4,5])
normalized_array=normalize_array(example_array)
print(normalized_array)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#(b)compute the min by max for each row for a numpy array 2d
import numpy as np
array_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
min_values = np.min(array_2d, axis=1)
max_values = np.max(array_2d, axis=1)
result = min_values / max_values
print(result)

[0.33333333 0.66666667 0.77777778]


In [2]:
8(a)#installing pandas
!pip install pandas

In [3]:
#import pandas and check the version
import pandas as pd
print(pd.__version__)

2.2.2


In [4]:
#create a series from a list,numpy array and dict
import pandas as pd
import numpy as np
print(pd.Series([1, 2, 3]))
print(pd.Series(np.array([4, 5, 6])))
print(pd.Series({'a': 7, 'b': 8, 'c': 9}))

0    1
1    2
2    3
dtype: int64
0    4
1    5
2    6
dtype: int64
a    7
b    8
c    9
dtype: int64


In [6]:
#convert the index of a series in to a column of a data frame
import pandas as pd
s=pd.Series([1,2,3,4,5])
df=s.to_frame().reset_index()
print(df)

   index  0
0      0  1
1      1  2
2      2  3
3      3  4
4      4  5


In [7]:
#combine many series to form a data frame
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([6,7,8,9,10])
df=pd.concat([s1,s2],axis=1)
print(s1)
print(s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     6
1     7
2     8
3     9
4    10
dtype: int64


In [10]:
#9(a)get the minimum,25thpercentile,median,75th,and max of a numeric series
import pandas as pd
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(s.describe(percentiles=[.25, .5, .75])[['min', '25%', '50%', '75%', 'max']])

min     1.00
25%     3.25
50%     5.50
75%     7.75
max    10.00
dtype: float64


In [12]:
#(b)get frequency counts of unique items of a series
import pandas as pd
data=[1,2,2,3,3,3,4,4,4,4]
s=pd.Series(data)
frequency_counts=s.value_counts()
print(frequency_counts)

4    4
3    3
2    2
1    1
Name: count, dtype: int64


In [13]:
#(c)bina numeric series to 10 groups of equal size
import pandas as pd
data=[1,2,3,4,5,6,7,8,9,10]
s=pd.Series(data)
groups=pd.qcut(s,q=10)
print(groups)

0    (0.999, 1.9]
1      (1.9, 2.8]
2      (2.8, 3.7]
3      (3.7, 4.6]
4      (4.6, 5.5]
5      (5.5, 6.4]
6      (6.4, 7.3]
7      (7.3, 8.2]
8      (8.2, 9.1]
9     (9.1, 10.0]
dtype: category
Categories (10, interval[float64, right]): [(0.999, 1.9] < (1.9, 2.8] < (2.8, 3.7] < (3.7, 4.6] < ... <
                                            (6.4, 7.3] < (7.3, 8.2] < (8.2, 9.1] < (9.1, 10.0]]


In [14]:
#(d)compute the euclidean distance between two series
import pandas as pd
import numpy as np
s1=pd.Series([1,2,3])
s2=pd.Series([4,5,6])
distance=np.linalg.norm(s1-s2)
print(f"euclidean distance:{distance}")

euclidean distance:5.196152422706632


In [15]:
#10(a)normalize all columns in a data frame
import pandas as pd
data={'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]}
df=pd.DataFrame(data)
df_normalized=(df-df.min())/(df.max()-df.min())
print(df_normalized)

     A    B    C
0  0.0  0.0  0.0
1  0.5  0.5  0.5
2  1.0  1.0  1.0


In [16]:
#(b)compute the correlation of each row with the succeed in grow
import pandas as pd
import numpy as np
data = {'col1': [1, 2, 3, 4, 5],
        'col2': [5, 4, 3, 2, 1],
        'col3': [2, 3, 4, 5, 6]}
df = pd.DataFrame(data)
correlation_row_succeeding_row = df.corrwith(df.shift(-1), axis=1)
print(correlation_row_succeeding_row)

0    0.960769
1    0.000000
2    0.755929
3    0.989743
4         NaN
dtype: float64


In [18]:
#(c)compute the autocorrelations of a numeric series
import pandas as pd
data=[1,2,3,4,5,6,7,8,9,10]
s=pd.Series(data)
autocorrelation= s.autocorr()
print(autocorrelation)

1.0
